"""ReadModel — the presentation-neutral view of a finished Creative Read.

One source of truth for every line a brand manager reads, so the terminal
report (batch_run.py) and the client-facing HTML (agent/report_html.py)
cannot drift apart on the honesty surfaces. The rule that motivates this
module: the client artifact may curate which FINDINGS it shows; it may
never drop a GUARDRAIL.

The guardrails carried here — each one exists because a specific way of
misreading the number was found in testing:

  * INCONCLUSIVE never shows an action rate       (spec §4)
  * A3  "would research" is reported separately, never folded into buy
  * A4  the per-cycle breakdown accompanies the blended headline, so the
        headline never hides its cycle-mix assumption
  * A7  the coherence warning when stated buy-intent contradicts the glance
  * A6  trust: HIGH needs >=2 within-target dispositions, else DIRECTIONAL
  * F3  the per-purpose launch-scope caveat (BETA / PARKED)
  * E3  the model-inferred disclaimer
  *     methodology flags, provisional dispositions, panel degradation

build_read_model() reads a finished run directory. It touches exactly:

    run.json            — config + the persisted Report (status='complete')
    replay_report.json  — the Report when the run was recovered by
                          replay_synthesis after a mid-run crash
    l3_summary.json     — segment behavioural distributions (the glance);
                          this is NOT carried on the Report

docs/v3_protocol.md is the protocol these numbers come from.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from agent.purpose import resolve_purpose
from agent.schema import Report

# ---- Shared presentation vocabulary -------------------------------------
# Imported by batch_run.py (terminal) and agent/report_html.py (client HTML).
# Changing a string here changes both renderers, which is the point.

DECISION_TAGLINE = {
    "SCALE": "Put spend behind it — no in-scope lever would materially lift it.",
    "ITERATE": "Target responds; a specific in-scope fix is leaking conversion. "
               "Fix it, re-run, then scale.",
    "RETARGET": "The creative works — for a different audience than it's aimed at. "
                "Fix the buy, not the ad.",
    "REBUILD": "The target rejects it on grounds no in-scope tweak fixes. "
               "Don't run as-is.",
    "INCONCLUSIVE": "The read isn't trustworthy yet — see why below.",
}

LEVER_HEADING = {
    "ITERATE": "THE FIX(ES)  (highest-leverage first):",
    "RETARGET": "RE-AIM + FIX  (highest-leverage first):",
    "REBUILD": "IF YOU REBUILD, what has to change:",
    "INCONCLUSIVE": "TO GET A TRUSTWORTHY READ:",
    "SCALE": "PROTECT ON SCALE-UP:",
}

CYCLE_LABEL = {
    "running_low": "running low",
    "mid_cycle": "mid-cycle",
    "just_bought": "just bought",
}
CYCLE_ORDER = ("running_low", "mid_cycle", "just_bought")

# v3 F3 — launch scope. Per-purpose scoring is validated to different depths:
# direct_sell + cold_hook are anchored; the rest run but their headline metric
# is not yet anchored by a per-purpose calibration run. We WARN, never block.
PURPOSE_SCOPE_NOTE = {
    "brand_building": (
        "BETA — brand-building scoring is provisional (resonance half only; "
        "brand-attribution is a known, flagged limitation). Trust the pains "
        "and the voice; treat the headline metric as directional."
    ),
    "awareness_informer": (
        "PARKED — informer scoring is not yet anchored by a per-purpose "
        "calibration run. The reactions are sound; the headline metric is "
        "unvalidated. Trust the pains and the voice, not the number."
    ),
    "retain_winback": (
        "PARKED — retain/win-back needs existing-customer (loyalist/lapsed) "
        "dispositions to score honestly; scoring is unvalidated. Trust the "
        "pains and the voice, not the number."
    ),
}

# v3 E3 — the one prominent, honest disclaimer. Every quote in a read is
# generated by a simulated persona reacting to the creative.
DISCLAIMER = (
    "Model-inferred read: every reaction and quote here is generated by a "
    "simulated persona, not collected from a real consumer. Read it as a "
    "pre-flight diagnostic, not a survey."
)

FUNNEL_OFF_NOTE = (
    "Projected funnel: off — heuristic_v1, not fitted to in-market outcomes. "
    "It is computed and logged for future calibration either way; re-run with "
    "--funnel to see the directional estimate."
)

# When --funnel was on, the projection exists but this view deliberately does
# not chart it: the numbers are heuristic_v1 and unfitted, so putting a funnel
# chart in front of a client would read as a forecast. Say so rather than
# letting the projection vanish without explanation.
FUNNEL_WITHHELD_NOTE = (
    "Projected funnel: computed for this run, but not charted here — "
    "heuristic_v1 is not fitted to in-market outcomes, so it is a directional "
    "estimate, not a forecast. It is in the run's l35_projection.json."
)


def humanize(label: str) -> str:
    return label.replace("_", " ")


def purpose_scope_note(purpose: str) -> str | None:
    """v3 F3: the launch-scope caveat for a purpose, or None when the purpose
    is active (direct_sell / cold_hook)."""
    return PURPOSE_SCOPE_NOTE.get(purpose)


def headline_metric_line(d) -> str:
    """The one number the brand manager reads, phrased for the ad's JOB.
    Direct-sell is byte-for-byte the v2.3 line; other jobs swap metric+frame."""
    preset = resolve_purpose(getattr(d, "purpose", "direct_sell") or "direct_sell")
    rate = f"{d.target_action_rate:.0%}"
    tail = (f"  —  {d.target_action_num} of {d.target_action_denom}"
            if d.target_action_denom else "")
    if preset.name == "direct_sell":
        who = (humanize(", ".join(d.within_dispositions))
               if d.within_dispositions else "your target")
        return f"  {rate} of your target ({who}) would buy{tail}."
    if preset.name == "cold_hook":
        return (f"  {rate} of a cold audience stopped and leaned in{tail}  "
                f"(vs scrolling past — the hook, not the sale).")
    if preset.name == "brand_building":
        return (f"  {rate} both felt it AND remembered the brand{tail}  "
                f"(engaged but mis-attributed doesn't count).")
    if preset.name == "awareness_informer":
        # breadth is a disposition COUNT: num of denom audience TYPES registered.
        return (f"  {d.target_action_num} of {d.target_action_denom} audience types "
                f"registered it as news ({rate})  (breadth of noticing, not sales).")
    # retain / others: a generic metric-labelled line.
    return f"  {rate} — {preset.metric_label}{tail}."


def trust_line(d) -> str:
    if d.trust == "HIGH":
        line = "Trust: HIGH"
        if len(d.within_dispositions) >= 2:
            line += f" — {len(d.within_dispositions)} within-target dispositions agree"
        if d.target_action_denom:
            line += f" ({d.target_action_denom} in the target sample)"
        return line + "."
    return ("Trust: DIRECTIONAL — thin evidence (one narrow audience engaged); "
            "treat as a lead, not a verdict.")


def inconclusive_lines(report: Report) -> list[str]:
    """Plain-language why + what-to-change for an INCONCLUSIVE read (spec §4).
    An untrustworthy read must NEVER show a confident action-rate headline —
    the number rests on the wrong people or an unreadable target."""
    flags = set(report.methodology_flags)
    if "pool_archetype_mismatch" in flags:
        why = ("the audience this ad targets isn't represented in your "
               "disposition library, so the read rests on the wrong people")
        fix = ("add a disposition profile that matches this ad's audience, "
               "then re-run")
    elif "target_unsignaled" in flags:
        why = ("the ad doesn't clearly signal who it's for — every audience "
               "read as a maybe")
        fix = ("clarify the creative's target, or declare the audience you're "
               "buying against, then re-run")
    else:
        why = (report.decision.rationale if report.decision else
               "the read isn't trustworthy on this pool")
        fix = "check that the audience you declared matches who the ad is for"
    return [
        "  We can't give you a trustworthy read on this creative yet.",
        f"  Why: {why}.",
        f"  To get a real read: {fix}.",
    ]


# ---- Glance -------------------------------------------------------------


@dataclass
class Glance:
    """What the thumb did in the 2-second encounter, for the within-target
    audience only. Sourced from L3 segment distributions, because the Report
    carries the decision numbers but not the raw action mix."""

    scroll_past: int = 0
    linger: int = 0
    tap_through: int = 0

    @property
    def n(self) -> int:
        return self.scroll_past + self.linger + self.tap_through

    def rate(self, key: str) -> float:
        return (getattr(self, key) / self.n) if self.n else 0.0

    def to_dict(self) -> dict:
        return {
            "scroll_past": self.scroll_past, "linger": self.linger,
            "tap_through": self.tap_through, "n": self.n,
        }


def _disposition_of_segment(segment_key: str) -> str:
    """Segment keys are '<disposition>::<chaos_band>' at the default
    disposition_chaos_band granularity, or a bare '<disposition>' at
    disposition granularity. Split exactly — never prefix-match, or two
    dispositions sharing a prefix silently merge."""
    return segment_key.split("::", 1)[0]


def within_target_glance(
    segment_distributions: dict, within_dispositions: list[str]
) -> Glance:
    """Sum the action mix across segments belonging to the within-target
    dispositions. An empty within-set yields an empty Glance (n=0), which
    every renderer must treat as 'no glance bar', not as 0%."""
    wanted = set(within_dispositions)
    g = Glance()
    for seg_key, dist in segment_distributions.items():
        if _disposition_of_segment(seg_key) not in wanted:
            continue
        counts = (dist or {}).get("counts", {}) or {}
        g.scroll_past += int(counts.get("scroll_past", 0))
        g.linger += int(counts.get("linger", 0))
        g.tap_through += int(counts.get("tap_through", 0))
    return g


# ---- The model ----------------------------------------------------------


@dataclass
class ReadModel:
    """Everything a renderer needs, already resolved. No renderer should
    reach past this into raw JSON — that is how guardrails get dropped."""

    # provenance
    run_id: str
    run_dir: Path
    report: Report
    report_source: str            # 'run.json' | 'replay_report.json'
    generated_at: str = ""

    # what was read
    asset_label: str = ""
    asset_path: Path | None = None
    category: str = ""
    account_id: str = ""
    brand_profile_id: str = ""
    declared_targeting: str = ""
    panel_size: int = 0

    # the job it was graded against
    purpose: str = "direct_sell"
    purpose_label: str = ""
    purpose_metric_label: str = ""
    scope_note: str | None = None          # F3

    # the decision surface
    decision_name: str = "INCONCLUSIVE"
    tagline: str = ""
    is_inconclusive: bool = True
    headline: str | None = None            # None when INCONCLUSIVE
    inconclusive: list[str] = field(default_factory=list)
    research_line: str | None = None       # A3
    coherence_warning: str | None = None   # A7
    cycle_rows: list[dict] = field(default_factory=list)   # A4
    champion_line: str | None = None
    narrow_frame_line: str | None = None
    trust: str = "DIRECTIONAL"
    trust_note: str = ""
    lever_heading: str = ""

    # the numbers
    glance: Glance = field(default_factory=Glance)
    within_dispositions: list[str] = field(default_factory=list)

    # honesty surfaces
    disclaimer: str = DISCLAIMER
    funnel_note: str | None = FUNNEL_OFF_NOTE
    panel_degraded: str | None = None
    # v2.1 two-axis audience match. declared_* / inferred_* are context; the
    # WARNING is the guardrail — the creative reads as aimed at someone other
    # than the audience being bought. On a brand manager's own ad the declared
    # targeting is real and often off, and a confident headline printed over a
    # silent mismatch is exactly the failure this exists to prevent.
    audience_mismatch: str | None = None
    declared_audience: str = ""
    inferred_audience: str = ""

    @property
    def within_label(self) -> str:
        return (humanize(", ".join(self.within_dispositions))
                if self.within_dispositions else "your target")


def _load_report(run_dir: Path) -> tuple[Report, dict, str]:
    """Resolve the Report from a finished run directory.

    Two legitimate sources: the normal path writes it into run.json at
    status='complete'; a run recovered by replay_synthesis after a mid-run
    crash writes replay_report.json instead. Fail LOUDLY when neither
    exists — rendering a blank report for a prospect is far worse than an
    error, and a crashed run is exactly the case that produces one.
    """
    run_json = run_dir / "run.json"
    if not run_json.exists():
        raise FileNotFoundError(f"no run.json in {run_dir} — not a run directory")
    raw = json.loads(run_json.read_text())

    payload = raw.get("report")
    if payload:
        return Report.from_dict(payload), raw, "run.json"

    replay = run_dir / "replay_report.json"
    if replay.exists():
        return Report.from_dict(json.loads(replay.read_text())), raw, "replay_report.json"

    raise ValueError(
        f"run {run_dir.name} carries no Report (status={raw.get('status')!r}). "
        "The run did not reach 'complete' and no replay_report.json exists. "
        "Recover it with replay_synthesis before rendering — do NOT render a "
        "partial read."
    )


def build_read_model(run_dir: str | Path) -> ReadModel:
    """Build the presentation model from a finished run directory."""
    run_dir = Path(run_dir)
    report, raw, source = _load_report(run_dir)
    config = raw.get("config", {}) or {}
    d = report.decision

    asset = config.get("asset", {}) or {}
    asset_path = Path(asset["image_path"]) if asset.get("image_path") else None
    spec = config.get("audience_spec", {}) or {}
    creative = config.get("creative_inputs", {}) or {}

    purpose = creative.get("purpose") or "direct_sell"
    preset = resolve_purpose(purpose)

    model = ReadModel(
        run_id=raw.get("run_id", run_dir.name),
        run_dir=run_dir,
        report=report,
        report_source=source,
        generated_at=raw.get("updated_at", ""),
        asset_label=asset.get("label", ""),
        asset_path=asset_path,
        category=config.get("category", ""),
        account_id=config.get("account_id", ""),
        brand_profile_id=config.get("brand_profile_id", ""),
        declared_targeting=config.get("declared_targeting", ""),
        panel_size=int(spec.get("panel_size") or 0),
        purpose=purpose,
        purpose_label=preset.label,
        purpose_metric_label=preset.metric_label,
        scope_note=purpose_scope_note(purpose),
        funnel_note=(FUNNEL_WITHHELD_NOTE if report.funnel_projection is not None
                     else FUNNEL_OFF_NOTE),
    )

    am = report.audience_match
    if am is not None:
        model.declared_audience = am.declared_summary or ""
        model.inferred_audience = am.inferred_summary or ""
        if am.verdict == "mismatched":
            model.audience_mismatch = am.message

    # Panel degradation is honesty-relevant on a client artifact: a read built
    # on a partially-landed panel must not look like a clean deterministic one.
    health = raw.get("panel_health") or {}
    if health.get("degraded"):
        model.panel_degraded = (
            f"{health.get('succeeded', '?')} of {health.get('expected', '?')} "
            "simulated respondents completed; a few dropped out mid-run. The "
            "read stands, but it rests on a slightly smaller sample than planned."
        )

    if d is None:
        # Legacy pre-2.3 report: no decision layer. Keep it honest rather than
        # inventing a decision — the bet ranking is all there is.
        model.decision_name = "INCONCLUSIVE"
        model.tagline = DECISION_TAGLINE["INCONCLUSIVE"]
        model.inconclusive = inconclusive_lines(report)
        model.lever_heading = LEVER_HEADING["INCONCLUSIVE"]
        return model

    model.decision_name = d.decision
    model.tagline = DECISION_TAGLINE.get(d.decision, "")
    model.trust = d.trust
    model.trust_note = trust_line(d)
    model.lever_heading = LEVER_HEADING.get(d.decision, "ACTIONS:")
    model.within_dispositions = list(d.within_dispositions)
    model.is_inconclusive = d.decision == "INCONCLUSIVE"

    if model.is_inconclusive:
        # Never surface an action rate here — the read is untrustworthy by
        # definition, even when target_action_rate happens to be non-None.
        model.inconclusive = inconclusive_lines(report)
    elif d.target_action_rate is not None:
        model.headline = headline_metric_line(d)
        # A3: the "would research" companion — reported SEPARATELY, never
        # folded into the buy headline. Buy-frame jobs only.
        if (d.research_rate is not None and d.research_denom
                and preset.name in ("direct_sell", "retain_winback")):
            model.research_line = (
                f"Separately, {d.research_rate:.0%} would look it up first "
                f"({d.research_num} of {d.research_denom}) — research, not a purchase."
            )
        if d.coherence_incoherent:
            model.coherence_warning = (
                "Coherence check: buy-now intent was stated, but every one of "
                "those people scrolled past without even stopping on the ad — "
                "treat the buy number with caution."
            )
        # A4: the mix-independent read — the per-cycle breakdown so the blended
        # headline never hides its cycle-mix assumption.
        for pos in CYCLE_ORDER:
            c = (d.by_cycle_position or {}).get(pos)
            if c:
                model.cycle_rows.append({
                    "key": pos, "label": CYCLE_LABEL[pos], "rate": c["rate"],
                    "num": c["num"], "denom": c["denom"],
                })
        if d.decision == "RETARGET" and d.champion_disposition:
            rate = (f"{d.champion_action_rate:.0%}"
                    if d.champion_action_rate is not None else "a higher rate")
            model.champion_line = (
                f"But the {humanize(d.champion_disposition)} — whom you are NOT "
                f"targeting — acts at {rate}. Right ad, wrong person."
            )
        elif d.decision in ("ITERATE", "REBUILD") and preset.audience_frame == "narrow":
            model.narrow_frame_line = (
                "It reaches no one else (everyone else scrolls — expected; "
                "tighten targeting)."
            )
    else:
        model.headline = None
        model.inconclusive = [f"  No trustworthy within-target read — {d.rationale}."]

    # The glance needs L3 — it is not carried on the Report.
    l3_path = run_dir / "l3_summary.json"
    if l3_path.exists() and model.within_dispositions:
        l3 = json.loads(l3_path.read_text())
        model.glance = within_target_glance(
            l3.get("segment_behavioral_distributions", {}) or {},
            model.within_dispositions,
        )

    return model
